= Conclusions

This thesis has presented the implementation and performance analysis of two distributed Agent-Based Models (ABMs): a misinformation diffusion model and a socio-epistemic knowledge spread model. The work was motivated by the growing relevance of large-scale social simulations, the need to understand the factors that determine the performance and scalability of distributed ABM frameworks and the need to optimize compute power in the era of data.

The selected models were chosen according to a set of criteria centered around performance evaluation. In particular, both models include an explicit network structure defining static or dynamic relationships between agents and expose parameters that allow systematic exploration of computational and communication costs. These characteristics made them suitable case studies for identifying performance bottlenecks in distributed simulations.

A detailed analysis of the original model implementations was conducted, including the identification of the conceptual correspondence between the original NetLogo implementations and the Repast HPC framework. Based on this analysis, parallel versions of both models were successfully developed using Repast HPC. Validation experiments demonstrated that the distributed implementations reproduced the behaviour of the original models with sufficient accuracy, providing confidence that the performance results are representative of the intended simulations. One of the main technical challenges of the Repast HPC implementations was the management and synchronization of ghost agents, which constitute a fundamental mechanism for maintaining consistency across distributed network partitions. The development of the socio-epistemic knowledge spread model also highlighted some limitations of the available framework. While the network projection was successfully implemented, the spatial grid component of the original model proved significantly more challenging to reproduce within the scope of this work. Consequently, the spatial movement and force-based mechanisms of the original model were omitted from the distributed implementation, allowing the study to focus on the network interaction component.

The performance analysis was conducted through the instrumentation of the simulation code using the TAU Performance System. Execution traces, execution times and memory-related metrics were collected for a broad range of experimental configurations. Parameter sweeps were performed to evaluate the influence of network topology, partitioning strategy, problem size, computational load and communication requirements on the overall performance of the models.

The results demonstrate that partitioning quality is the dominant factor affecting the performance of distributed network-based agent simulations. Community-aware partitioning strategies significantly reduce ghost synchronization overhead by preserving network locality and minimizing inter-rank communication. In contrast, poorly partitioned networks may generate communication costs that exceed the computational savings obtained through parallelization, leading to slower execution than the corresponding sequential implementation.

The effectiveness of the partitioning strategy was found to depend strongly on the structural characteristics of the underlying network. In particular, the average clustering coefficient exhibited a significant influence on performance, as highly clustered networks naturally form communities that can be partitioned efficiently. Networks with weaker community structures require a larger number of ghost agents and therefore incur greater synchronization overhead. By comparison, variations in network size, computational workload and message size produced results that were generally consistent with the expected scaling behaviour.

The analysis of the number of MPI ranks further highlighted the interaction between parallelization and communication overhead. Increasing the number of ranks only produced performance improvements when the reduction in computation time exceeded the additional synchronization costs. Consequently, the scalability of the distributed implementation depends not only on the available computational resources but also on the ability of the partitioning strategy to preserve locality within the network.

One observation that could not be fully explained was the increase in measured ghost synchronization time when additional computational workload was introduced. Although the communication pattern of the model remained unchanged, synchronization times exhibited a noticeable increase. Further investigation would be required to determine whether this behaviour originates from measurement methodology, MPI runtime effects, operating-system scheduling, or interactions between computation and communication phases.

A particularly relevant finding of this work is that the dominant performance bottleneck differs significantly between the two studied models, despite both being network-based distributed agent simulations. In the misinformation diffusion model, performance is primarily limited by communication volume. Consequently, reducing the number of ghost agents through effective community-based partitioning directly decreases synchronization overhead and leads to substantial performance improvements. In contrast, the socio-epistemic knowledge spread model is not primarily constrained by the cost of exchanging messages between MPI ranks, but rather by the computational effort required to identify, maintain and synchronize the extended neighbourhood information needed by the model. Since agents may require information from neighbours up to three connections away, the management of ghost agents becomes a significant source of overhead, often outweighing the communication costs themselves. This distinction highlights that scalability in distributed network-based ABMs depends not only on the amount of inter-process communication, but also on the complexity of the mechanisms required to support that communication.

Overall, the results confirm that distributed execution can significantly improve the performance of network-based agent simulations, emphasizing the importance of network topology and its partitioning strategy selection when developing scalable distributed ABMs.

#v(10pt)
*Future Work*

Extending the Repast HPC implementation to support spatial grid projections would allow a more faithful reproduction of models that combine network interactions with spatial dynamics. This extension would make it possible to evaluate the performance impact of simultaneously managing network and spatial projections in distributed environments.

Also, alternative partitioning strategies should be investigated. In particular, approaches that explicitly consider the total number of MPI ranks during partition construction may achieve better load balancing and lower communication overhead than the community-based strategy employed in this work.

The performance analysis could be extended beyond execution-time measurements by incorporating hardware performance counters through the Performance Application Programming Interface (PAPI). Such measurements would provide additional insight into cache behaviour, memory accesses and processor utilization, enabling a deeper understanding of the observed bottlenecks.

Finally, other performance-analysis tools, such as Scalasca @ScalascaSoftware, could be employed to obtain a finer-grained characterization of MPI communication patterns. In particular, these tools may facilitate a more accurate measurement of synchronization overhead and help explain some of the behaviours observed during the scalability experiments @ScalascaManual.

#v(10pt)
*Aknowledgments*

I would like to express my gratitude to my supervisors, Andreu Moreno and Josep Jorba, for their guidance, support and valuable feedback throughout the development of this thesis. Their expertise and encouragement have been fundamental in shaping this work and overcoming the challenges encountered during the research process.

Finally, I would like to thank everyone who supported me during the completion of my master's studies and this thesis.
